name: Build to "release" branch

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  release:
    name: "Update release branch"
    uses: humanmade/hm-github-actions/.github/workflows/build-and-release-node.yml@a9a243d6c42fbff4a967d7ce0a6b307bc77251b7 # v0.1.0
    with:
      # Default build action `npm run build` is sufficient.
      node_version: 20
      source_branch: main
      release_branch: release
      built_asset_paths: dist
